
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AND COLUMN COMMA CREATE END FROM INSERT INTO LFPARENTH OP RGPARENTH SELECT SET STAR TABLE VALUES WHEREexpressions : expression\n                    | expressions expressionexpression :  exp_select\n                    | exp_create\n                    | exp_insertexp_select : SELECT columns FROM COLUMN END\n                    | SELECT STAR FROM COLUMN END\n                    | SELECT STAR FROM COLUMN WHERE exp_condition END\n                    | SELECT columns FROM COLUMN WHERE exp_condition ENDexp_create : CREATE TABLE COLUMN LFPARENTH columns RGPARENTH ENDexp_insert : INSERT INTO COLUMN exp_insert_endexp_condition : COLUMN OP COLUMN\n                     | COLUMN OP COLUMN AND exp_conditionexp_insert_end : VALUES LFPARENTH columns RGPARENTH END\n                      | LFPARENTH columns RGPARENTH VALUES LFPARENTH columns RGPARENTH ENDcolumns : COLUMN\n               | COLUMN COMMA columns'
    
_lr_action_items = {'SELECT':([0,1,2,3,4,5,9,24,27,29,41,42,43,47,53,],[6,6,-1,-3,-4,-5,-2,-11,-6,-7,-9,-8,-10,-14,-15,]),'CREATE':([0,1,2,3,4,5,9,24,27,29,41,42,43,47,53,],[7,7,-1,-3,-4,-5,-2,-11,-6,-7,-9,-8,-10,-14,-15,]),'INSERT':([0,1,2,3,4,5,9,24,27,29,41,42,43,47,53,],[8,8,-1,-3,-4,-5,-2,-11,-6,-7,-9,-8,-10,-14,-15,]),'$end':([1,2,3,4,5,9,24,27,29,41,42,43,47,53,],[0,-1,-3,-4,-5,-2,-11,-6,-7,-9,-8,-10,-14,-15,]),'STAR':([6,],[12,]),'COLUMN':([6,13,14,15,16,17,23,26,28,30,32,40,48,49,],[11,18,19,20,11,22,11,11,34,34,11,46,11,34,]),'TABLE':([7,],[13,]),'INTO':([8,],[14,]),'FROM':([10,11,12,21,],[15,-16,17,-17,]),'RGPARENTH':([11,21,31,33,38,50,],[-16,-17,37,39,44,52,]),'COMMA':([11,],[16,]),'LFPARENTH':([18,19,25,45,],[23,26,32,48,]),'VALUES':([19,39,],[25,45,]),'END':([20,22,35,36,37,44,46,51,52,],[27,29,41,42,43,47,-12,-13,53,]),'WHERE':([20,22,],[28,30,]),'OP':([34,],[40,]),'AND':([46,],[49,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expressions':([0,],[1,]),'expression':([0,1,],[2,9,]),'exp_select':([0,1,],[3,3,]),'exp_create':([0,1,],[4,4,]),'exp_insert':([0,1,],[5,5,]),'columns':([6,16,23,26,32,48,],[10,21,31,33,38,50,]),'exp_insert_end':([19,],[24,]),'exp_condition':([28,30,49,],[35,36,51,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expressions","S'",1,None,None,None),
  ('expressions -> expression','expressions',1,'p_statement_expr','interpreter.py',240),
  ('expressions -> expressions expression','expressions',2,'p_statement_expr','interpreter.py',241),
  ('expression -> exp_select','expression',1,'p_expression_start','interpreter.py',248),
  ('expression -> exp_create','expression',1,'p_expression_start','interpreter.py',249),
  ('expression -> exp_insert','expression',1,'p_expression_start','interpreter.py',250),
  ('exp_select -> SELECT columns FROM COLUMN END','exp_select',5,'p_expression_select','interpreter.py',254),
  ('exp_select -> SELECT STAR FROM COLUMN END','exp_select',5,'p_expression_select','interpreter.py',255),
  ('exp_select -> SELECT STAR FROM COLUMN WHERE exp_condition END','exp_select',7,'p_expression_select','interpreter.py',256),
  ('exp_select -> SELECT columns FROM COLUMN WHERE exp_condition END','exp_select',7,'p_expression_select','interpreter.py',257),
  ('exp_create -> CREATE TABLE COLUMN LFPARENTH columns RGPARENTH END','exp_create',7,'p_expression_create','interpreter.py',271),
  ('exp_insert -> INSERT INTO COLUMN exp_insert_end','exp_insert',4,'p_expression_insert','interpreter.py',283),
  ('exp_condition -> COLUMN OP COLUMN','exp_condition',3,'p_expression_condition','interpreter.py',297),
  ('exp_condition -> COLUMN OP COLUMN AND exp_condition','exp_condition',5,'p_expression_condition','interpreter.py',298),
  ('exp_insert_end -> VALUES LFPARENTH columns RGPARENTH END','exp_insert_end',5,'p_expresssion_insert_end','interpreter.py',304),
  ('exp_insert_end -> LFPARENTH columns RGPARENTH VALUES LFPARENTH columns RGPARENTH END','exp_insert_end',8,'p_expresssion_insert_end','interpreter.py',305),
  ('columns -> COLUMN','columns',1,'p_expression_columns','interpreter.py',311),
  ('columns -> COLUMN COMMA columns','columns',3,'p_expression_columns','interpreter.py',312),
]
